version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "third_party/pigweed/repo"
      - dependency-name: "third_party/mbedtls/repo"
      - dependency-name: "third_party/openthread/repo"
